default: &default
  adapter: 'sqlite3'
  database: 'db/racqueteers.sqlite'

development:
  <<: *default

production:
  adapter: postgresql
  database: racqueteers_production
  pool: 5
  timeout: 5000
